theme: jekyll-theme-minimal
title: Decoding the DNA of our characters on the silver screen
description: Project ADAcadabra1001010
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
  - title: Example2
    url: example2
